In [1]:
import torch

In [14]:
import torch

# 创建一个形状为 B x S x P x 2C 的张量，假设 B=4, S=3, P=5, C=2
B, S, P, C = 4, 3, 5, 2
tensor = torch.randn(B, S, P, 2 * C)

# 打印原始张量的形状
print(f"Original tensor shape: {tensor.shape}")

# 取[:,:,0]的操作
result = tensor[:, :, 3:]

# 打印结果的形状
print(f"Result tensor shape after slicing [:,:,0]: {result.shape}")


Original tensor shape: torch.Size([4, 3, 5, 4])
Result tensor shape after slicing [:,:,0]: torch.Size([4, 3, 2, 4])


In [19]:
import torch
print(torch.eye(4)[None])

tensor([[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]])


In [23]:
extra_row = torch.tensor([0, 0, 0, 1]).view(1, 1, 1, 4)
print(extra_row)

tensor([[[[0, 0, 0, 1]]]])


In [27]:
a = torch.randn(3,4)
print(a)
print(a[1,2])
print(a[1][2])

tensor([[ 1.1370, -0.1237, -1.0423,  0.1253],
        [ 0.2938, -1.0731,  0.4261,  2.1498],
        [-0.8498,  0.9855,  0.5165,  1.9853]])
tensor(0.4261)
tensor(0.4261)


In [34]:
g = (x for x in range(10) if x % 2 == 0)

print(next(g))
print(next(g))
print(next(g))

0
2
4


In [ ]:
def fib(max):
    n, a, b = 0, 0, 1
    while n < max:
        yield b
        a, b = b, a + b
        n = n + 1
    return 'done'
f = fib(6)

<function __main__.fib(max)>